export enum EMovieStaff {
    DIRECTOR = 'DIRECTOR',
    WRITER = 'WRITER',
    PRODUCER = 'PRODUCER',
    OPERATOR = 'OPERATOR',
    COMPOSER = 'COMPOSER',
    DESIGN = 'DESIGN',
    EDITOR = 'EDITOR',
}
