import {
    EMovieMainStaff,
    EMovieBox,
    EMovieAwards,
    EMovieDistributions,
    EMovieImages,
    EMovieFacts,
    EMovieStaff,
    EReviewsSelect,
    EMpaaRating,
} from 'Common/Enums';

export const T = {
    date: 'D MMMM YYYY',
    dateAndTime: 'DD MMMM YYYY | hh:mm',
    Pages: {
        backToMovie: 'Информация о фильме',
        MovieDefault: 'Обзор',
        Facts: {
            label: 'Факты',
            route: 'facts',
            empty: 'Интересные факты о фильме не найдены',
        },
        Images: {
            label: 'Изображения',
            route: 'images',
            empty: 'Нет данных об изображениях',
        },
        Reviews: {
            label: 'Рецензии',
            route: 'reviews',
            empty: 'Рецензии на фильм отсутствуют',
        },
        Staff: {
            label: 'Создатели',
            route: 'staff',
            empty: 'Нет данных о создателях',
        },
        Videos: {
            label: 'Видео',
            route: 'videos',
            empty: 'Видеоматериалы отсутствуют',
        },
        Awards: {
            label: 'Награды',
            route: 'awards',
            empty: 'Нет данных о наградах',
        },
        Distributions: {
            label: 'Прокат',
            route: 'distributions',
            empty: 'Нет данных о прокате',
        },
    },
    Movie: {
        movieTitle: 'О фильме',
        serialTitle: 'О сериале',
        year: 'Год производства',
        country: 'Страна',
        slogan: 'Слоган',
        genre: 'Жанр',
        age: 'Возраст',
        ratingMPAA: 'Рейтинг MPAA',
        duration: 'Время',
        castTitle: 'В ролях',
        countable: {
            grade: ['оценка', 'оценки', 'оценок'],
            actors: ['актер', 'актера', 'актеров'],
            seasons: ['сезон', 'сезона', 'сезонов'],
        },
        Reviews: {
            SortingSelect: {
                label: 'Сортировать:',
                SelectDictionary: {
                    [EReviewsSelect.DATE_ASC]: 'По возрастанию даты',
                    [EReviewsSelect.DATE_DESC]: 'По убыванию даты',
                    [EReviewsSelect.USER_POSITIVE_RATING_ASC]: 'По возрастанию позитивных рецензий',
                    [EReviewsSelect.USER_POSITIVE_RATING_DESC]: 'По убыванию позитивных рецензий',
                    [EReviewsSelect.USER_NEGATIVE_RATING_ASC]: 'По возрастанию негативных рецензий',
                    [EReviewsSelect.USER_NEGATIVE_RATING_DESC]: 'По убыванию негативных рецензий',
                },
            },
            Types: {
                all: 'Всего',
                positive: 'Позитивные',
                negative: 'Негативные',
                neutral: 'Нейтральные',
            },
        },
        Staff: {
            MainDictionary: {
                [EMovieMainStaff.DIRECTOR]: 'Режиссер',
                [EMovieMainStaff.WRITER]: 'Сценарий',
                [EMovieMainStaff.PRODUCER]: 'Продюсер',
                [EMovieMainStaff.OPERATOR]: 'Оператор',
                [EMovieMainStaff.COMPOSER]: 'Композитор',
                [EMovieMainStaff.DESIGN]: 'Художник',
                [EMovieMainStaff.EDITOR]: 'Монтаж',
            },
            Dictionary: {
                [EMovieStaff.DIRECTOR]: ['Режиссер', 'Режиссеры'],
                [EMovieStaff.ACTOR]: ['Актер', 'Актеры'],
                [EMovieStaff.PRODUCER]: ['Продюсер', 'Продюсеры'],
                [EMovieStaff.WRITER]: ['Сценарист', 'Сценаристы'],
                [EMovieStaff.OPERATOR]: ['Оператор', 'Операторы'],
                [EMovieStaff.COMPOSER]: ['Композитор', 'Композиторы'],
                [EMovieStaff.DESIGN]: ['Художник', 'Художники'],
                [EMovieStaff.EDITOR]: ['Монтажер', 'Монтажеры'],
                [EMovieStaff.PRODUCER_USSR]: ['Директор фильма', 'Директора фильма'],
                [EMovieStaff.TRANSLATOR]: ['Переводчик', 'Переводчики'],
                [EMovieStaff.VOICE_DIRECTOR]: ['Режиссер дубляжа', 'Режиссеры дубляжа'],
                [EMovieStaff.UNKNOWN]: ['Другой', 'Другие'],
            },
        },
        Box: {
            Dictionary: {
                [EMovieBox.BUDGET]: 'Бюджет',
                [EMovieBox.MARKETING]: 'Маркетинг',
                [EMovieBox.USA]: 'Сборы в США',
                [EMovieBox.RUS]: 'Сборы в России',
                [EMovieBox.WORLD]: 'Сборы в мире',
            },
        },
        Awards: {
            Dictionary: {
                [EMovieAwards.OSCAR]: 'Оскар',
                [EMovieAwards.GOLDEN_GLOBE]: 'Золотой глобус',
                [EMovieAwards.BRITISH_ACADEMY]: 'Британская академия',
                [EMovieAwards.CESAR]: 'Сезар',
                [EMovieAwards.ACTORS_GUILD_AWARDS]: 'Премия Гильдии актеров',
                [EMovieAwards.NIKA]: 'Ника',
                [EMovieAwards.GOLDEN_EAGLE]: 'Золотой орел',
                [EMovieAwards.SATURN]: 'Сатурн',
                [EMovieAwards.GOYA]: 'Гойя',
                [EMovieAwards.EMMY]: 'Эмми',
                [EMovieAwards.ASIAN_FILM_ACADEMY]: 'Азиатская киноакадемия',
                [EMovieAwards.EUROPEAN_FILM_ACADEMY]: 'Европейская киноакадемия',
                [EMovieAwards.MTV]: 'Премия канала «MTV»',
                [EMovieAwards.MTV_RUSSIA]: 'Кинонаграды «MTV-Россия»',
                [EMovieAwards.GOLDEN_RASPBERRY]: 'Золотая малина',
                [EMovieAwards.GEORGE_MELIES]: 'Жорж',
                [EMovieAwards.CANNES_FILM_FESTIVAL]: 'Каннский кинофестиваль',
                [EMovieAwards.BERLIN_FILM_FESTIVAL]: 'Берлинский кинофестиваль',
                [EMovieAwards.VENICE_FILM_FESTIVAL]: 'Венецианский кинофестиваль',
                [EMovieAwards.MOSCOW_FILM_FESTIVAL]: 'ММКФ',
                [EMovieAwards.KARLOVY_VARY_FILM_FESTIVAL]: 'Карловы Вары',
                [EMovieAwards.KINOTAVR]: 'Кинотавр',
                [EMovieAwards.SAN_SEBASTIAN_FILM_FESTIVAL]: 'Сан-Себастьян',
                [EMovieAwards.SUNDANCE_FILM_FESTIVAL]: 'Сандэнс',
            },
        },
        Distributions: {
            Dictionary: {
                [EMovieDistributions.COUNTRY_SPECIFIC]: 'Премьера в России',
                [EMovieDistributions.WORLD_PREMIER]: 'Мировая премьера',
                [EMovieDistributions.PREMIERE]: 'Премьеры в странах',
                [EMovieDistributions.ALL]: 'На DVD',
            },
        },
        Facts: {
            Dictionary: {
                [EMovieFacts.BLOOPER]: 'Ляпы',
                [EMovieFacts.FACT]: 'Факты',
            },
        },
        Images: {
            Dictionary: {
                [EMovieImages.STILL]: 'Кадры',
                [EMovieImages.SHOOTING]: 'Съемки',
                [EMovieImages.POSTER]: 'Постеры',
                [EMovieImages.FAN_ART]: 'Фан-арты',
                [EMovieImages.PROMO]: 'Промо',
                [EMovieImages.CONCEPT]: 'Концепты',
                [EMovieImages.WALLPAPER]: 'Обои',
                [EMovieImages.COVER]: 'Обложки',
                [EMovieImages.SCREENSHOT]: 'Скриншоты',
            },
        },
        MpaaRatng: {
            [EMpaaRating.g]: 'Нет возрастных ограничений',
            [EMpaaRating.pg]: 'Рекомендуется присутствие родителей',
            [EMpaaRating.pg13]: 'Детям до 13 лет просмотр не желателен',
            [EMpaaRating.r]: 'Лицам до 17 лет обязательно присутствие взрослого',
            [EMpaaRating.nc17]: 'Лицам до 18 лет просмотр запрещен',
        },
    },
    Person: {
        title: 'О персоне',
        profession: 'Карьера',
        growth: 'Рост',
        birthday: 'Дата рождения',
        birthPlace: 'Место рождения',
        death: 'Дата смерти',
        deathPlace: 'Место смерти',
        Spouses: {
            female: 'Супруга',
            male: 'Супруг',
            plural: 'Супруги',
            childs: {
                single: 'ребёнок',
                plural: 'детей',
            },
        },
        filmsCount: 'Всего фильмов',
        bestFilms: 'Лучшие фильмы',
    },
    Persons: {
        searchPlaceholder: 'Актеры, режиссёры,и т.д.',
    },
};
